version: '3'
services:
  web:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - .:/usr/openarms
    links:
      - mongo
      - keycloak
  mongo:
    image: "mongo:3.4.9"
  keycloak:
    image: "jboss/keycloak:3.3.0.CR2"
    ports:
      - "8080:8080"
