version: '3'
services:
  web:
    volumes:
      - .:/usr/openarms
    command: [ "npm", "start", "--", "--keycloak-ui", "keycloak-ui.json", "--keycloak-backend", "keycloak-backend.json", "--db-url", "mongodb://mongo:27017/openarms", "--dev" ]
